import { Plugin, ProfessionType } from '../shared/types';

// ── 所有内置插件定义 ──────────────────────────────────────
// 插件全部打包在客户端，无需联网下载

export const ALL_PLUGINS: Plugin[] = [

  // ── 通用插件（所有职业） ────────────────────────────────
  {
    id: 'word-counter',
    name: 'word-counter',
    displayName: '实时字数统计',
    version: '1.0.0',
    description: '实时显示字数、字符数、阅读时长，支持自定义写作目标',
    author: '启文团队',
    category: 'utility',
    tags: ['统计', '写作'],
    isEnabled: true,
    isInstalled: true,
    isPaid: false,
    price: 0,
    icon: '📊',
    entryPoint: 'word-counter',
    permissions: ['read-documents'],
    settings: { goal: 1000, showInStatusBar: true },
    settingsSchema: [
      { key: 'goal', label: '写作目标（字）', type: 'number', default: 1000 },
      { key: 'showInStatusBar', label: '状态栏显示', type: 'boolean', default: true },
    ],
    installedAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'focus-timer',
    name: 'focus-timer',
    displayName: '番茄专注',
    version: '1.0.0',
    description: '番茄工作法计时器，帮助保持专注。25分钟工作+5分钟休息',
    author: '启文团队',
    category: 'utility',
    tags: ['专注', '效率', '计时'],
    isEnabled: true,
    isInstalled: true,
    isPaid: false,
    price: 0,
    icon: '🍅',
    entryPoint: 'focus-timer',
    permissions: [],
    settings: { workMinutes: 25, breakMinutes: 5, autoStart: false },
    settingsSchema: [
      { key: 'workMinutes', label: '工作时长（分钟）', type: 'number', default: 25 },
      { key: 'breakMinutes', label: '休息时长（分钟）', type: 'number', default: 5 },
      { key: 'autoStart', label: '自动开始下一轮', type: 'boolean', default: false },
    ],
    installedAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'quick-note',
    name: 'quick-note',
    displayName: '快速便签',
    version: '1.0.0',
    description: '侧边栏快速记录灵感、待办，随时调出不打断写作流',
    author: '启文团队',
    category: 'utility',
    tags: ['便签', '灵感', '待办'],
    isEnabled: true,
    isInstalled: true,
    isPaid: false,
    price: 0,
    icon: '📝',
    entryPoint: 'quick-note',
    permissions: ['write-documents'],
    settings: { pinned: false },
    settingsSchema: [],
    installedAt: Date.now(),
    updatedAt: Date.now(),
  },

  // ── 学术研究插件 ────────────────────────────────────────
  {
    id: 'citation-manager',
    name: 'citation-manager',
    displayName: '引用格式生成',
    version: '1.2.0',
    description: '支持 APA、MLA、Chicago、GB/T7714 等格式，一键生成引用和参考文献列表',
    author: '启文团队',
    category: 'reference',
    tags: ['引用', '参考文献', '学术'],
    isEnabled: true,
    isInstalled: true,
    isPaid: false,
    price: 0,
    icon: '📚',
    entryPoint: 'citation-manager',
    permissions: ['read-references', 'write-documents'],
    settings: { defaultFormat: 'APA', autoInsert: true },
    settingsSchema: [
      {
        key: 'defaultFormat', label: '默认引用格式', type: 'select', default: 'APA',
        options: [
          { label: 'APA 7th', value: 'APA' },
          { label: 'MLA 9th', value: 'MLA' },
          { label: 'Chicago 17th', value: 'Chicago' },
          { label: 'GB/T 7714-2015', value: 'GB' },
        ],
      },
      { key: 'autoInsert', label: '自动插入文内引用', type: 'boolean', default: true },
    ],
    installedAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'outline-builder',
    name: 'outline-builder',
    displayName: '论文大纲助手',
    version: '1.0.0',
    description: '可拖拽的论文大纲构建器，支持章节管理和字数规划',
    author: '启文团队',
    category: 'writing',
    tags: ['大纲', '论文', '结构'],
    isEnabled: true,
    isInstalled: true,
    isPaid: false,
    price: 0,
    icon: '🏗️',
    entryPoint: 'outline-builder',
    permissions: ['read-documents', 'write-documents'],
    settings: {},
    settingsSchema: [],
    installedAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'keyword-extractor',
    name: 'keyword-extractor',
    displayName: '关键词提取',
    version: '1.0.0',
    description: '从文档中自动提取高频关键词，辅助摘要写作和标签管理',
    author: '启文团队',
    category: 'ai',
    tags: ['关键词', '摘要', '分析'],
    isEnabled: true,
    isInstalled: true,
    isPaid: false,
    price: 0,
    icon: '🔑',
    entryPoint: 'keyword-extractor',
    permissions: ['read-documents'],
    settings: { maxKeywords: 10 },
    settingsSchema: [
      { key: 'maxKeywords', label: '最大关键词数量', type: 'number', default: 10 },
    ],
    installedAt: Date.now(),
    updatedAt: Date.now(),
  },

  // ── 法律工作插件 ────────────────────────────────────────
  {
    id: 'clause-library',
    name: 'clause-library',
    displayName: '条款模板库',
    version: '1.0.0',
    description: '内置500+常用法律条款模板，涵盖合同、协议、声明等，一键插入',
    author: '启文团队',
    category: 'writing',
    tags: ['条款', '合同', '模板'],
    isEnabled: true,
    isInstalled: true,
    isPaid: false,
    price: 0,
    icon: '⚖️',
    entryPoint: 'clause-library',
    permissions: ['write-documents'],
    settings: { category: 'all' },
    settingsSchema: [
      {
        key: 'category', label: '默认分类', type: 'select', default: 'all',
        options: [
          { label: '全部', value: 'all' },
          { label: '合同通用', value: 'contract' },
          { label: '劳动合同', value: 'labor' },
          { label: '购销合同', value: 'purchase' },
          { label: '保密协议', value: 'nda' },
        ],
      },
    ],
    installedAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'legal-checker',
    name: 'legal-checker',
    displayName: '法律术语检查',
    version: '1.0.0',
    description: '检查文档中的法律用语规范性，标记模糊表达和潜在风险条款',
    author: '启文团队',
    category: 'writing',
    tags: ['检查', '规范', '法律'],
    isEnabled: true,
    isInstalled: true,
    isPaid: false,
    price: 0,
    icon: '🔍',
    entryPoint: 'legal-checker',
    permissions: ['read-documents'],
    settings: { autoCheck: false, highlightRisk: true },
    settingsSchema: [
      { key: 'autoCheck', label: '自动检查', type: 'boolean', default: false },
      { key: 'highlightRisk', label: '高亮风险词', type: 'boolean', default: true },
    ],
    installedAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'case-timeline',
    name: 'case-timeline',
    displayName: '案件时间线',
    version: '1.0.0',
    description: '可视化案件事件时间线，支持节点标注和关键事实梳理',
    author: '启文团队',
    category: 'utility',
    tags: ['时间线', '案件', '梳理'],
    isEnabled: true,
    isInstalled: true,
    isPaid: false,
    price: 0,
    icon: '📅',
    entryPoint: 'case-timeline',
    permissions: ['read-documents', 'write-documents'],
    settings: {},
    settingsSchema: [],
    installedAt: Date.now(),
    updatedAt: Date.now(),
  },

  // ── 教育培训插件 ────────────────────────────────────────
  {
    id: 'lesson-planner',
    name: 'lesson-planner',
    displayName: '教案规划器',
    version: '1.0.0',
    description: '结构化教案模板，含教学目标、重难点、教学环节等标准字段',
    author: '启文团队',
    category: 'writing',
    tags: ['教案', '教学', '规划'],
    isEnabled: true,
    isInstalled: true,
    isPaid: false,
    price: 0,
    icon: '📋',
    entryPoint: 'lesson-planner',
    permissions: ['write-documents'],
    settings: { subject: '' },
    settingsSchema: [
      { key: 'subject', label: '默认学科', type: 'text', default: '' },
    ],
    installedAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'quiz-generator',
    name: 'quiz-generator',
    displayName: '题目生成器',
    version: '1.0.0',
    description: '从文档内容自动生成选择题、填空题、判断题，支持导出题库',
    author: '启文团队',
    category: 'ai',
    tags: ['题目', '测验', '题库'],
    isEnabled: true,
    isInstalled: true,
    isPaid: false,
    price: 0,
    icon: '❓',
    entryPoint: 'quiz-generator',
    permissions: ['read-documents', 'write-documents'],
    settings: { questionTypes: ['choice', 'blank'], count: 5 },
    settingsSchema: [
      { key: 'count', label: '每次生成题目数', type: 'number', default: 5 },
    ],
    installedAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'mindmap-preview',
    name: 'mindmap-preview',
    displayName: '思维导图',
    version: '1.0.0',
    description: '将文档标题结构自动转换为思维导图，支持展开/折叠节点',
    author: '启文团队',
    category: 'utility',
    tags: ['思维导图', '结构', '可视化'],
    isEnabled: true,
    isInstalled: true,
    isPaid: false,
    price: 0,
    icon: '🗺️',
    entryPoint: 'mindmap-preview',
    permissions: ['read-documents'],
    settings: { autoSync: true },
    settingsSchema: [
      { key: 'autoSync', label: '自动同步文档结构', type: 'boolean', default: true },
    ],
    installedAt: Date.now(),
    updatedAt: Date.now(),
  },

  // ── 医疗健康插件 ────────────────────────────────────────
  {
    id: 'medical-template',
    name: 'medical-template',
    displayName: '病历模板库',
    version: '1.0.0',
    description: '内置标准病历、门诊记录、手术记录等模板，符合医疗文书规范',
    author: '启文团队',
    category: 'writing',
    tags: ['病历', '医疗', '模板'],
    isEnabled: true,
    isInstalled: true,
    isPaid: false,
    price: 0,
    icon: '🏥',
    entryPoint: 'medical-template',
    permissions: ['write-documents'],
    settings: { department: '' },
    settingsSchema: [
      { key: 'department', label: '科室', type: 'text', default: '' },
    ],
    installedAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'drug-reference',
    name: 'drug-reference',
    displayName: '药品速查',
    version: '1.0.0',
    description: '本地药品数据库，快速查询常用药物剂量、禁忌、相互作用',
    author: '启文团队',
    category: 'reference',
    tags: ['药品', '查询', '参考'],
    isEnabled: true,
    isInstalled: true,
    isPaid: false,
    price: 0,
    icon: '💊',
    entryPoint: 'drug-reference',
    permissions: [],
    settings: {},
    settingsSchema: [],
    installedAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'icd-lookup',
    name: 'icd-lookup',
    displayName: 'ICD 编码查询',
    version: '1.0.0',
    description: 'ICD-10 / ICD-11 疾病编码本地查询，支持中英文双语检索',
    author: '启文团队',
    category: 'reference',
    tags: ['ICD', '编码', '诊断'],
    isEnabled: true,
    isInstalled: true,
    isPaid: false,
    price: 0,
    icon: '🔬',
    entryPoint: 'icd-lookup',
    permissions: [],
    settings: { version: 'ICD-10' },
    settingsSchema: [
      {
        key: 'version', label: 'ICD 版本', type: 'select', default: 'ICD-10',
        options: [{ label: 'ICD-10', value: 'ICD-10' }, { label: 'ICD-11', value: 'ICD-11' }],
      },
    ],
    installedAt: Date.now(),
    updatedAt: Date.now(),
  },

  // ── 内容创作插件 ────────────────────────────────────────
  {
    id: 'readability-score',
    name: 'readability-score',
    displayName: '可读性分析',
    version: '1.0.0',
    description: '分析文章可读性、句子长度分布、段落节奏，提供优化建议',
    author: '启文团队',
    category: 'writing',
    tags: ['可读性', '分析', '优化'],
    isEnabled: true,
    isInstalled: true,
    isPaid: false,
    price: 0,
    icon: '📈',
    entryPoint: 'readability-score',
    permissions: ['read-documents'],
    settings: {},
    settingsSchema: [],
    installedAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'character-tracker',
    name: 'character-tracker',
    displayName: '人物关系图',
    version: '1.0.0',
    description: '追踪故事中的人物、关系、出场章节，可视化人物关系网络',
    author: '启文团队',
    category: 'utility',
    tags: ['人物', '故事', '关系'],
    isEnabled: true,
    isInstalled: true,
    isPaid: false,
    price: 0,
    icon: '👥',
    entryPoint: 'character-tracker',
    permissions: ['read-documents', 'write-documents'],
    settings: {},
    settingsSchema: [],
    installedAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'style-checker',
    name: 'style-checker',
    displayName: '文风检测',
    version: '1.0.0',
    description: '检测写作风格一致性，标记重复用词、被动语态过多等问题',
    author: '启文团队',
    category: 'writing',
    tags: ['文风', '检测', '写作'],
    isEnabled: true,
    isInstalled: true,
    isPaid: false,
    price: 0,
    icon: '✨',
    entryPoint: 'style-checker',
    permissions: ['read-documents'],
    settings: { language: 'zh-CN' },
    settingsSchema: [],
    installedAt: Date.now(),
    updatedAt: Date.now(),
  },
];

// ── 按职业推荐插件 ID ──────────────────────────────────────
export const PROFESSION_PLUGIN_MAP: Record<ProfessionType, string[]> = {
  researcher: [
    'citation-manager',
    'outline-builder',
    'keyword-extractor',
    'word-counter',
    'focus-timer',
    'quick-note',
  ],
  lawyer: [
    'clause-library',
    'legal-checker',
    'case-timeline',
    'word-counter',
    'focus-timer',
    'quick-note',
  ],
  teacher: [
    'lesson-planner',
    'quiz-generator',
    'mindmap-preview',
    'word-counter',
    'focus-timer',
    'quick-note',
  ],
  doctor: [
    'medical-template',
    'drug-reference',
    'icd-lookup',
    'word-counter',
    'focus-timer',
    'quick-note',
  ],
  writer: [
    'readability-score',
    'character-tracker',
    'style-checker',
    'word-counter',
    'focus-timer',
    'quick-note',
  ],
  general: [
    'word-counter',
    'focus-timer',
    'quick-note',
    'mindmap-preview',
    'keyword-extractor',
    'readability-score',
  ],
};

/** 根据职业获取推荐插件列表（已安装并启用） */
export function getPluginsForProfession(profession: ProfessionType): Plugin[] {
  const ids = PROFESSION_PLUGIN_MAP[profession] ?? PROFESSION_PLUGIN_MAP.general;
  return ALL_PLUGINS
    .filter(p => ids.includes(p.id))
    .map(p => ({
      ...p,
      isEnabled: true,
      isInstalled: true,
      installedAt: Date.now(),
    }));
}

/** 获取所有未在当前职业推荐中的插件（可手动安装） */
export function getAvailablePlugins(profession: ProfessionType): Plugin[] {
  const ids = PROFESSION_PLUGIN_MAP[profession] ?? [];
  return ALL_PLUGINS
    .filter(p => !ids.includes(p.id))
    .map(p => ({ ...p, isEnabled: false, isInstalled: false, installedAt: null }));
}
